version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test_backend:
    docker:
      - image: circleci/node:16.10  
    steps:
      - checkout  
      - run:
          name: Install backend dependencies
          command: npm --prefix ./Backend/ install  
      - run:
          name: Set environment variables 
          command: |
            echo "Setting Firebase environment variable"
            echo $FIREBASE_SERVICE_ACCOUNT > ./Backend/.env # יצירת קובץ env
      - run:
          name: Run backend tests
          command: |
            echo "Running all tests"
            npm --prefix ./Backend/ run test  
      - run:
          name: Check test results
          command: |
            if [ $? -ne 0 ]; then
              echo "Tests failed. Exiting pipeline."
              exit 1
            else
              echo "All tests passed successfully!"
            fi

  deploy_backend:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run:
          name: Install backend dependencies for deployment
          command: npm --prefix ./Backend/ install  
      - run:
          name: Set environment variables for deployment 
          command: |
            echo "Setting Firebase environment variable for deployment"
            echo $FIREBASE_SERVICE_ACCOUNT > ./Backend/.env
      - run:
          name: Trigger deploy on Render
          command: |
            curl -X POST "https://app-project-management.onrender.com"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test_backend  
      - deploy_backend:
          requires:
            - build_and_test_backend
